apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /tmp/pv001
    type: ""
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
