apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb-bot
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: mariadb-bot
    app.kubernetes.io/version: "0.13"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: snowdrop-bot
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: mariadb-bot
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: mariadb-bot
    app.kubernetes.io/version: "0.13"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: snowdrop-bot
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
      - configmaps
      - events
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: mariadb-bot
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: mariadb-bot
    app.kubernetes.io/version: "0.13"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: snowdrop-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mariadb-bot
subjects:
  - kind: ServiceAccount
    name: mariadb-bot