kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: snowdrop-bot-mariadb
  namespace: bot
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: mariadb-bot
    app.kubernetes.io/version: "0.13"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: snowdrop-bot
spec:
  serviceName: "mariadb"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mariadb
    spec:
      containers:
        - name: mariadb
#          image: mariadb:10.5.8
          image: quay.io/centos7/mariadb-103-centos7
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3306
              name: mariadbdb
          envFrom:
            - configMapRef:
                name: snowdrop-bot-mariadb-config
            - secretRef:
                name: mariadb-root-password
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadbdb
      volumes:
        - name: mariadbdb
          persistentVolumeClaim:
            claimName: snowdrop-bot-mariadb-pvc
