apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: bot
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: mariadb-bot
    app.kubernetes.io/version: "0.13"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: snowdrop-bot
spec:
  type: NodePort
  ports:
    - name: mariadb
      port: 3306
      protocol: TCP
  selector:
    app.kubernetes.io/name: mariadb
status:
  loadBalancer: {}
